package by.newsportal.news.controller;

public enum CommandName {
    GO_TO_MAIN_PAGE,
    GO_TO_ADD_NEWS_PAGE,
    GO_TO_OFFER_NEWS_PAGE,
    GO_TO_LIST_NEWS_OFFER_PAGE,
    GO_TO_AFTER_AUTHORIZATION_PAGE,
    REGISTRATION_PAGE,
    REGISTRATION_NEW_USER,
    AUTHORIZATION_PAGE,
    AUTHORIZATION_USER,
    CHANGE_LOCAL,
    UPDATE_NEWS,
    UPDATE_NEWS_PAGE,
    DELETE_NEWS,
    ADD_NEWS,
    OFFER_NEWS,
    ADD_NEWS_TO_HOME_PAGE,
    UNKNOWN_COMMAND
}
